### ISSUE TITLE
missing pip dependencies

### ISSUE THREAD

**Issue by rithwikbabu** [Athe-kunal/SEC-QA-Agent#1]

**Comment by Athe-kunal** [comment]
Hi @rithwikbabu 
Sorry, can you provide some more information? Also, are you installing the packages in requirements.txt?

**Comment by rithwikbabu** [comment]
Yeah, the fastapi version was not compatible with chroma db. Switching it to fastapi==0.85.1 solved this issue. 
Wandb & sentence_transformers are missing.

**Comment by Athe-kunal** [comment]
Thanks @rithwikbabu. I have pushed the changes to resolve the pip dependencies. Please let me know about other suggestions.
