### ISSUE TITLE
Unstructured IO might not be good enough 

### ISSUE THREAD

**Issue by BenGraWarBuf** [Athe-kunal/SEC-QA-Agent#2]
i Like what you are doing here. But i dont think the unstructured library is good enough out the box for what you are trying to do. not all 10-K or 10-Q fillings have the sections in the specific format that  unstructured SEC Prepline uses, and therefore this script will fail to download and parse correctly some of those filings. Take Intel's latest 10-K as an example. they don't list any of the report's sections in the prescribed manner and therefore i doubt the methodology here can capture all that information and input it correctly to the vector store. unfortunately, the SEC does not impose a strict filling format and there are a bunch of companies that do the same thing as intel.

**Comment by Athe-kunal** [comment]
I see @BenGraWarBuf 
It is a great point and thanks for bringing that up. How do you suggest we go about doing this then? Currently, the pipeline ensures that are picking from the best possible sources. How can we reliably get the relevant context here? Any suggestions?
Naive similarity search won't work as it can't be reliable

**Comment by Athe-kunal** [comment]
Hi @BenGraWarBuf 
I tried with Intel for the year 2022 with unstructured. I was able to get section-wise data with Unstructured for Intel. So please check it out. Thanks
